name: Pip

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: Build with Pip
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        # windows-latest, macos-latest,
        platform: [ubuntu-latest]
        python-version: ["3.8", "3.12"]

    steps:
    - uses: actions/checkout@v5

    - uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}

    #- name: Set min macOS version
    #  if: runner.os == 'macOS'
    #  run: |
    #    echo "MACOSX_DEPLOYMENT_TARGET=10.14" >> $GITHUB_ENV

    - name: Install Xvfb
      run: sudo apt update && sudo apt-get install -y xvfb

    - name: Set up Xvfb
      run: |
        echo "Xvfb is set up"
        echo "DISPLAY=:99" >> $GITHUB_ENV
        echo "Xvfb started on display :99"
        (nohup Xvfb :99 -screen 0 1280x1024x24 -nolisten tcp -nolisten unix &)

    - name: Build and install
      run: |
        sudo apt update && sudo apt install libpcl-dev
        python -m pip install pytest numpy
        pip install --verbose .

    - name: Test
      run: python -m pytest
